//
// Created by Administrator on 2019-8-6.
//

#ifndef STUDIOBLETEST_STD_IMAGE_CONFIG_H
#define STUDIOBLETEST_STD_IMAGE_CONFIG_H

#define STB_IMAGE_IMPLEMENTATION

#endif //STUDIOBLETEST_STD_IMAGE_CONFIG_H
